name: Build with CMake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Set up Android NDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: '22.1.7171670'

      - name: Build with CMake
        run: |
          cmake -Bbuild -H.
          cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: imguijniroot
          path: build/*.so
